### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by riqui0130** [riqui0130/chat-space#8]
#IPアドレス
18.180.87.75

**Comment by mutorisa** [comment]
甲田さん、ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
